[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-source-register'

[[plugins]]
repo = 'shun/ddu-source-rg'

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo='Shougo/ddu-commands.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'flow6852/ddu-source-qf'

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_event = ['BufEnter']
hook_source = '''
call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'uiParams': {
    \      'ff': {
    \         'filterFloatingPosition': 'top',
    \         'prompt': '> ',
    \         'split': 'horizontal',
    \         'splitDirection': 'topleft',
    \         'startFilter': 'v:true',
    \         'winWidth': '&columns / 2 - 2',
    \         'previewFloating': 'v:true',
    \         'previewHeight': '&lines - 8',
    \         'previewWidth': '&columns / 2 - 2',
    \         'previewRow': '1',
    \         'previewCol': '&columns / 2 + 1',
    \         'previewSplit': 'vertical'
    \      },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   },
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \       'ignoreCase': 'true',
    \     },
    \   },
    \   'filterParams': {
    \      'matcher_substring': {
    \          'highlightMatched': 'Search',
    \      },
    \   },
    \ })

call ddu#custom#patch_local('file_rec', {
    \   'sources': [
    \     {
    \       'name': 'file_rec',
    \       'params': {
    \         'ignoredDirectories': ['.git', 'vendor', '.next']
    \       }
    \     },
    \   ],
    \ })

call ddu#custom#patch_local('grep', {
    \   'sourceParams' : {
    \     'rg' : {
    \       'args': ['--column', '--no-heading', '--color', 'never'],
    \     },
    \   },
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:false,
    \     }
    \   },
    \ })

call ddu#custom#patch_local('qf', {
    \   'ui': 'ff',
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \     },
    \   },
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:false,
    \       'highlights': {'selected': 'Statement'},
    \       'winCol': &columns/8,
    \       'winWidth': 3*&columns/4,
    \       'winRow': &lines/8,
    \       'winHeight': 3*&lines/8,
    \       'autoAction': {'name':'preview'},
    \       'previewFloating': v:true,
    \       'previewCol': &columns/8,
    \       'previewWidth': 3*&columns/4,
    \       'previewRow': 7*&lines/8-1,
    \       'previewHeight': 3*&lines/8,
    \       }
    \   },
    \   'kindOptions': {
    \     'custom-list': {
    \       'defaultAction': 'open',
    \     },
    \   }
    \ })


	autocmd FileType ddu-ff call s:ddu_ff_my_settings()
	function s:ddu_ff_my_settings() abort
	  nnoremap <buffer> <CR>
	  \ <Cmd>call ddu#ui#do_action('itemAction')<CR>
    nnoremap <buffer> <C-h>
    \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'leftabove vertical new'}})<CR>
    nnoremap <buffer> <C-j>
    \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'split'}})<CR>
    nnoremap <buffer> <C-k>
    \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'leftabove split'}})<CR>
    nnoremap <buffer> <C-l>
    \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
    nnoremap <buffer> <C-t>
    \ <Cmd>call ddu#ui#do_action('itemAction', {'name': 'open', 'params': {'command': 'tab drop'}})<CR>
	  nnoremap <buffer> <Space>
	  \ <Cmd>call ddu#ui#do_action('toggleSelectItem')<CR>
	  nnoremap <buffer> i
	  \ <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
	  nnoremap <buffer> q
	  \ <Cmd>call ddu#ui#do_action('quit')<CR>
	endfunction
  nnoremap <C-j>j :call ddu#start({'name': 'file_rec'})<CR>
  nnoremap <C-j>g
    \ <Cmd>call ddu#start({
    \   'name': 'grep',
    \   'sources': [{
    \     'name': 'rg',
    \   }],
    \   'sourceParams': {
    \     'rg': {
    \       'input': expand('<cword>'),
    \     },
    \   },
    \ })<CR>

  nnoremap <C-j>s
    \ <Cmd>call ddu#start({
    \   'volatile': v:false,
    \   'sources': [{
    \     'name': 'rg',
    \   }],
    \   'sourceParams': {
    \     'rg': {
    \       'input': input('Pattern: '),
    \     },
    \   },
    \ })<CR>

  let format='%T|%p|%y|%t'
  nnoremap <C-j>f
    \ <Cmd> call ddu#start({
    \ 'name': 'qf', 'sources': [
    \ {'name': 'qf',
    \ 'params': {'what': {'title': ':vimgrep'},
    \            'isSubst': v:true,
    \            'format': format,
    \            'dup': v:true}},
    \ {'name': 'qf',
    \ 'params': {'what': {'title': ':lvimgrep'},
    \            'isSubst': v:true,
    \            'format': format,
    \            'nr': 0,
    \            'dup': v:true}}]})<CR>
'''
