[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'lambdalisue/unite-grep-vcs'

[[plugins]]
repo = 'lambdalisue/unite-grep-vcs'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugins'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'thinca/vim-qfhl'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'vim-scripts/javacomplete'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = "aklt/plantuml-syntax"

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'thoughtbot/vim-rspec'

[[plugins]]
repo = 'itmammoth/run-rspec.vim'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
